pull_request_rules:
  - name: automatic update
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
    actions:
      update:
  - name: Automatic merge
    conditions:
      - "#approved-reviews-by>=2"
      - check-success=lint (ubuntu-latest, 3.10)
      - check-success=build_test_job (ubuntu-latest, 3.7, xoscar)
      - check-success=build_test_job (ubuntu-latest, 3.8, xoscar)
      - check-success=build_test_job (ubuntu-latest, 3.9, xoscar)
      - check-success=build_test_job (ubuntu-latest, 3.10, xoscar)
      - check-success=build_test_job (macos-latest, 3.7, xoscar)
      - check-success=build_test_job (macos-latest, 3.10, xoscar)
      - check-success=build_test_job (windows-latest, 3.7, xoscar)
      - check-success=build_test_job (windows-latest, 3.10, xoscar)
      - check-success=codecov/project
      # - check-success=docs/readthedocs.org:xoscar
      - base=main
    actions:
      merge:
        method: squash
