name: xoscar-test
channels:
  - defaults
dependencies:
  - numpy<2.0.0
  - cloudpickle
  - coverage
  - cython
  - mock
  - pyarrow
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pytest-timeout
  - pytest-forked
  - scipy
  - pandas
  - numexpr
  - scikit-learn
  - psutil
  - tornado
  - defusedxml
  - pyyaml
  - black
  - tqdm
  - fsspec
  - flake8
  - pillow
  - lz4
  - sqlalchemy
  - tqdm
  - openpyxl
  - pip

  - pip:
    - uvloop>=0.14.0; sys.platform!="win32"
