name: xoscar-test
channels:
  - defaults
dependencies:
  - numpy
  - cloudpickle
  - coverage
  - cython
  - mock
  - pyarrow
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pytest-timeout
  - pytest-forked
  - scipy
  - pandas
  - numexpr
  - scikit-learn
  - psutil
  - tornado
  - defusedxml
  - pyyaml
  - black
  - tqdm
  - fsspec
  - flake8
  - pillow
  - lz4
  - sqlalchemy
  - tqdm
  - openpyxl
  - pip

  - pip:
    - uvloop>=0.21.0; sys_platform!="win32" and python_version<"3.14"
    - uvloop>=0.22.1; sys_platform!="win32" and python_version>="3.14"
